- hosts: localhost
  tasks:
    - gatekeeper.rego.def_vars:
        create_policy: True
        vars:
          requirements_yml: '[req.name | req := input.project.requirements.collections[_]]'
          _builtin_and_deps: 'array.concat(["ansible.builtin"], requirements_yml)'

    - gatekeeper.rego.def_rule:
        name: detect_missing_dependencies
        args: task
        steps:
        - fqcn := task.module_fqcn
        - collection := get_module_collection_name(fqcn)
        - not collection in _builtin_and_deps
        return: collection

    - gatekeeper.rego.def_rule:
        name: get_module_collection_name
        args: fqcn
        steps:
        - contains(fqcn, ".")
        - parts := split(fqcn, ".")
        - coll := concat(".", [parts[0], parts[1]])
        return: coll
    
    - gatekeeper.rego.def_rule:
        type: filter
        name: missing_dependencies
        steps:
        - task := input.taskfiles[_].tasks[_]
        - x := detect_missing_dependencies(task)
        key: x

    - gatekeeper.rego.def_rule:
        type: if
        name: has_missing_dependencies
        steps:
        - count(missing_dependencies) > 0

    - gatekeeper.rego.eval:
        project: firewall_role

